CREATE TABLE project
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    uid         UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE,
    code        VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    name        VARCHAR(255) NOT NULL,
    status      VARCHAR(255) NOT NULL,
    CONSTRAINT  project_id_pkey PRIMARY KEY (id, uid)
);

create table employee
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    uid        UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE,
    email      VARCHAR(255),
    first_name VARCHAR(255) NOT NULL,
    job_title  VARCHAR(255),
    last_name  VARCHAR(255) NOT NULL,
    status     VARCHAR(255) NOT NULL,
    surname    VARCHAR(255),
    username   VARCHAR(255),
    CONSTRAINT employee_id_pkey PRIMARY KEY (id, uid)
);

CREATE TABLE project_team
(
    employee_id   BIGINT NOT NULL REFERENCES employee (id),
    project_id    BIGINT NOT NULL REFERENCES project (id),
    role_employee VARCHAR(255) NOT NULL,
    CONSTRAINT project_team_id_pkey PRIMARY KEY (employee_id, project_id)
);

CREATE TABLE task
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    uid             UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE,
    date_of_created DATE NOT NULL,
    date_of_update  DATE NOT NULL,
    deadline        DATE NOT NULL,
    description     TEXT,
    execution_time  INTEGER      NOT NULL,
    name            VARCHAR(255) NOT NULL,
    status          VARCHAR(255) NOT NULL,
    author          BIGINT       NOT NULL REFERENCES public.employee (id),
    project_id      BIGINT       NOT NULL REFERENCES public.project (id),
    performer       BIGINT       NOT NULL REFERENCES public.employee (id),
    CONSTRAINT task_id_pkey PRIMARY KEY (id, uid)
);

CREATE TABLE project_file
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    uid         UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE,
    filename    TEXT    NOT NULL,
    project_id  BIGINT  NOT NULL REFERENCES public.project (id),
    CONSTRAINT  project_file_id_pkey PRIMARY KEY (id, uid)
);

CREATE TABLE task_file
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    uid         UUID DEFAULT uuid_generate_v4() NOT NULL UNIQUE,
    filename    TEXT    NOT NULL,
    task_id     BIGINT  NOT NULL REFERENCES public.task (id),
    CONSTRAINT  task_file_id_pkey PRIMARY KEY (id, uid)
);
